-- ============================================================
-- SQL Helpers — Run these in Supabase SQL Editor
-- ============================================================

-- ── RPC: increment_points ─────────────────────────────────
-- Used by points service as a safe atomic update
CREATE OR REPLACE FUNCTION increment_points(p_student_code TEXT, p_points INT)
RETURNS VOID AS $$
BEGIN
  UPDATE students
  SET points = GREATEST(0, points + p_points)
  WHERE student_code = p_student_code;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── RPC: execute_safe_insert ──────────────────────────────
-- Used by Import page for SQL import
-- IMPORTANT: Only allows INSERT statements as safety measure
CREATE OR REPLACE FUNCTION execute_safe_insert(sql_query TEXT)
RETURNS VOID AS $$
DECLARE
  upper_sql TEXT;
BEGIN
  upper_sql := UPPER(TRIM(sql_query));

  -- Only allow INSERT statements
  IF NOT (upper_sql LIKE 'INSERT%') THEN
    RAISE EXCEPTION 'Only INSERT statements are allowed';
  END IF;

  -- Block dangerous keywords
  IF upper_sql LIKE '%DROP%' OR
     upper_sql LIKE '%TRUNCATE%' OR
     upper_sql LIKE '%DELETE%' OR
     upper_sql LIKE '%ALTER%' OR
     upper_sql LIKE '%GRANT%' OR
     upper_sql LIKE '%REVOKE%' OR
     upper_sql LIKE '%UPDATE%' THEN
    RAISE EXCEPTION 'Dangerous SQL command detected';
  END IF;

  EXECUTE sql_query;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute to authenticated users
GRANT EXECUTE ON FUNCTION execute_safe_insert(TEXT) TO authenticated;

-- ── RPC: get_monthly_attendance_count ────────────────────
-- Fast aggregate for dashboard
CREATE OR REPLACE FUNCTION get_monthly_attendance_count(p_month TEXT)
RETURNS INT AS $$
BEGIN
  RETURN (
    SELECT COUNT(*)::INT
    FROM attendance
    WHERE TO_CHAR(date, 'YYYY-MM') = p_month
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── VIEW: leaderboard ─────────────────────────────────────
CREATE OR REPLACE VIEW leaderboard AS
SELECT
  student_code,
  name,
  stage,
  photo_url,
  points,
  RANK() OVER (ORDER BY points DESC) as rank
FROM students
WHERE status = '1' AND active = true
ORDER BY points DESC;

-- ── VIEW: attendance_summary ──────────────────────────────
CREATE OR REPLACE VIEW attendance_summary AS
SELECT
  s.student_code,
  s.name,
  s.stage,
  COUNT(a.id) AS total_attendance,
  COUNT(CASE WHEN TO_CHAR(a.date, 'YYYY-MM') = TO_CHAR(CURRENT_DATE, 'YYYY-MM')
             THEN 1 END) AS month_attendance
FROM students s
LEFT JOIN attendance a ON a.student_id = s.student_code
WHERE s.status = '1' AND s.active = true
GROUP BY s.student_code, s.name, s.stage;

-- ── Enable Realtime on all tables ────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE students;
ALTER PUBLICATION supabase_realtime ADD TABLE attendance;
ALTER PUBLICATION supabase_realtime ADD TABLE points_log;

-- ── SEED: Insert first admin ──────────────────────────────
-- Run AFTER creating the admin in Supabase Dashboard > Auth > Users
-- Replace with your actual admin email
/*
INSERT INTO admins (name, email, role)
VALUES ('مارك ميدهات', 'your-email@gmail.com', 'super_admin')
ON CONFLICT (email) DO NOTHING;
*/

-- ── SEED: Test student data ───────────────────────────────
/*
INSERT INTO students (student_code, name, phone, parent_phone, stage, birthday, confessor, status, active, points)
VALUES
  ('REG-TEST01', 'يوسف مارك أنطون', '01012345678', '01098765432', 'الصف الأول الإعدادي',  '2012-06-15', 'لوناسيرق', '1', true, 5),
  ('REG-TEST02', 'مريم بطرس جرجس', '01112345678', '01212345678', 'الصف الثاني الثانوي',   '2009-03-20', 'لوناسيرق', '1', true, 8),
  ('REG-TEST03', 'بيشوي سامح ميلاد', '01012349999', '01098761111', 'الصف الثالث الإعدادي', '2011-11-01', 'لوناتاوضروس', '1', true, 3);

-- Manually set QR codes (normally auto-generated by trigger)
UPDATE students SET qr_code = uuid_generate_v4()::TEXT WHERE qr_code IS NULL AND status = '1';
*/
